list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/card/card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/content/content_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/div/div_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/header/header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/label/label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/spinner/spinner_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/timehead/timehead_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/audioSettingsCard/audioSettingsCard_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/connectionSettingsCard/connectionSettingsCard_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/gameSettingsCard/gameSettingsCard_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/playerSettingsCard/playerSettingsCard_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/Monopoly_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/Monopoly.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/about/about_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/add_card/add_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/game_start/game_start_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/settings/settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/welcome/welcome_gen.c)